-- ↓8 rooms, and pictures are 2 * 8 = 16 rows
INSERT INTO rooms (name, summary, description, price, image_url, large_image_url, capacity) VALUES 
('Okinawa Room', 
 'Tropical paradise with ocean views and Ryukyuan elegance for a serene escape.',
 'Experience the ultimate tropical getaway in our Okinawa Room. Surrounded by crystal-clear turquoise waters and lush greenery, this room offers a serene escape from the everyday hustle. Enjoy breathtaking ocean views right from your balcony while feeling the gentle Pacific breeze. Our room features traditional Ryukyuan aesthetic touches combined with modern luxury, ensuring a comfortable and culturally rich stay. Whether you are looking for a romantic sunset or a peaceful morning by the shore, this space provides the perfect atmosphere for unforgettable memories in Japan''s southern paradise.', 
 250.00, 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/1.png', 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/1-lg.png', 2),

('Salt Flat Reflection Room', 
 'A breathtaking retreat inspired by the infinite reflections of vast salt flats.', 
 'Immerse yourself in the ethereal beauty of our Salt Flat Reflection Room. Designed to capture the surreal magic of the Salar de Uyuni, this space features minimalist decor and expansive mirrors that create an illusion of infinite horizon. The cool, crisp tones of the room evoke a sense of pure tranquility, mirroring the perfect stillness of the salt crust after a light rain. Guests can experience a unique blend of modern comfort and natural wonder, as the daylight shifts across the pristine white surfaces. Whether you are seeking a moment of deep reflection or simply want to feel as though you are walking on clouds, this room offers a once-in-a-lifetime atmosphere that blurs the line between heaven and earth.', 
 120.00, 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/2.png', 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/2-lg.png', 2),

('Cancun Room', 
 'A vibrant getaway with turquoise waters and the energetic spirit of Cancun.', 
 'Escape to the sun-drenched shores of the Yucatan Peninsula with our Cancun Room. This space is a celebration of Caribbean luxury, featuring a bright and airy design that mirrors the sparkling turquoise of the Mexican coastline. Relax on furniture inspired by coastal living while enjoying the warm, tropical ambiance created by natural textures and limestone accents. The room offers a perfect balance of relaxation and excitement, capturing the essence of Cancun''s world-famous beaches and lively cultural heritage. Whether you are unwinding after a day of exploring ancient Mayan ruins or simply soaking in the coastal vibes from your window, this room provides a vibrant sanctuary for your tropical dreams.', 
 200.00, 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/3.png', 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/3-lg.png', 4),

('Sunken Ship Room', 
 'A unique room where rusted iron meets marine life and hidden ocean history.', 
 'Dive into a world of maritime mystery with our Sunken Ship Room. This uniquely themed suite is designed to resemble the interior of a legendary vessel resting on the ocean floor. Featuring weathered wood textures, brass accents, and gentle ambient lighting that mimics rays of sunlight filtering through deep water, this room offers an immersive experience like no other. Discover the thrill of sleeping amidst the reimagined ruins of a historic wreck, surrounded by decor inspired by lost treasures and colorful coral reefs. The atmosphere captures the haunting yet beautiful silence of the deep sea, making it the perfect escape for those seeking adventure and tranquility in one. Whether you are a fan of naval history or simply want to feel the ocean''s embrace, this room tells a story of the sea that will linger in your heart long after you leave.', 
 500.00, 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/4.png', 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/4-lg.png', 2),

('Bali Island Room', 
 'A tranquil oasis of healing, inspired by lush jungles and serene temples.', 
 'Rejuvenate your soul in our Bali Island Room, a sanctuary of peace designed to bring the magic of Ubud to your stay. Adorned with hand-carved wooden accents, bamboo textures, and warm tropical hues, this room captures the essence of Indonesian hospitality. Large windows invite a soft, natural glow that illuminates the intricate Balinese decor, creating an atmosphere of deep relaxation and mindfulness. Imagine yourself surrounded by the scent of frangipani and the distant sound of trickling water as you unwind in this exotic retreat. The space is thoughtfully curated to provide a perfect escape from the modern world, blending traditional artistry with contemporary comfort. Whether you are looking for a meditative morning or a restful night, the Bali Island Room offers a spiritual journey that nourishes the heart and mind.', 
 80.00, 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/5.png', 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/5-lg.png', 5),

('Mangrove Swamp Room', 
 'A mystical sanctuary where life’s roots create a peaceful, vibrant emerald world.', 
 'Step into the enchanting realm of our Mangrove Swamp Room, a unique escape that celebrates the intersection of two worlds. The interior features deep forest greens, earthy wooden textures, and soft, dappled lighting that mimics the sun breaking through a thick canopy. Inspired by the resilient beauty of coastal wetlands, the decor includes organic shapes and intricate root-like designs that wrap the space in a protective, natural embrace. Listen to the metaphorical whisper of the tides as you relax in a room that feels both grounded and ethereal. This space is a tribute to the ''lungs of the ocean,'' offering a calm, oxygen-rich atmosphere for those who seek to reconnect with nature''s untamed spirit. Whether you are mesmerized by the complex beauty of the ecosystem or simply need a quiet place to breathe, this room provides a lush, revitalizing haven far from the urban jungle.', 
 344.00, 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/6.png', 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/6-lg.png', 6),

('Deep Sea Room', 
 'A serene midnight-blue escape where soft bioluminescent glows meet calm depths.', 
 'Descend into a world of absolute peace with our Deep Sea Room. This suite is an architectural tribute to the mysterious bathypelagic zone, featuring deep indigo walls, velvet textures, and subtle bioluminescent lighting accents that glow like rare creatures of the abyss. The design prioritizes a quiet, cocoon-like atmosphere, shielding you from the noise of the surface world. Soft, undulating light patterns dance across the ceiling, mimicking the movement of water miles below the waves. It is a space designed for deep sleep and profound introspection, where the weight of the world seems to float away. Whether you are mesmerized by the dark elegance of the ocean''s floor or simply seeking the quietest corner of our hotel, the Deep Sea Room offers a sublime immersion into the heart of the blue planet.', 
 389.00, 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/7.png', 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/7-lg.png', 7),

('Mediterranean Room', 
 'A sun-drenched sanctuary of white-washed walls and timeless azure elegance.', 
 'Experience the radiant charm of the coast in our Mediterranean Room. Inspired by the iconic architecture of Santorini and the Amalfi Coast, this room is a symphony of crisp whites and vibrant blues. The design features arched doorways, terracotta tiling, and rustic linen fabrics that breathe with the Mediterranean breeze. Flooded with natural light, the space creates an uplifting and airy atmosphere that invites you to slow down and savor the moment. Every detail, from the hand-painted ceramics to the scent of dried lavender and citrus, is curated to transport you to a seaside villa overlooking the sparkling Aegean. Whether you are dreaming of a summer getaway or simply want to bask in a sun-kissed retreat, this room offers a slice of European paradise.', 
 499.00, 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/8.png', 
 'https://raw.githubusercontent.com/Flying-WhaleShark/HotelBooking_UI/main/src/assets/img/rooms/8-lg.png', 8);